"""table

Revision ID: 66c8b8cce411
Revises: 
Create Date: 2025-04-16 20:20:00.353604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c8b8cce411'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistypecontainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expected', sa.String(length=1), nullable=True),
    sa.Column('typed', sa.String(length=1), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistypecontainer_id'), 'mistypecontainer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mistypecontainer_id'), table_name='mistypecontainer')
    op.drop_table('mistypecontainer')
    # ### end Alembic commands ###
