# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 87, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 20pt \"Ubuntu\";\n"
"color: rgb(61, 56, 70);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.email_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.email_lineEdit.setStyleSheet("Padding:10px;\n"
"border-radius:5px;\n"
"")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout.addWidget(self.email_lineEdit)
        self.username_lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.username_lineEdit_2.setStyleSheet("Padding:10px;\n"
"border-radius:5px;\n"
"")
        self.username_lineEdit_2.setObjectName("username_lineEdit_2")
        self.verticalLayout.addWidget(self.username_lineEdit_2)
        self.password_lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.password_lineEdit_3.setStyleSheet("Padding:10px;\n"
"border-radius:5px;\n"
"")
        self.password_lineEdit_3.setObjectName("password_lineEdit_3")
        self.verticalLayout.addWidget(self.password_lineEdit_3)
        self.confirm_password_lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.confirm_password_lineEdit_4.setStyleSheet("Padding:10px;\n"
"border-radius:5px;\n"
"")
        self.confirm_password_lineEdit_4.setObjectName("confirm_password_lineEdit_4")
        self.verticalLayout.addWidget(self.confirm_password_lineEdit_4)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.create_account_button = QtWidgets.QPushButton(self.frame_3)
        self.create_account_button.setObjectName("create_account_button")
        self.verticalLayout_3.addWidget(self.create_account_button)
        self.register_b_login = QtWidgets.QPushButton(self.frame_3)
        self.register_b_login.setObjectName("register_b_login")
        self.verticalLayout_3.addWidget(self.register_b_login)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 87, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Keystroke Improver"))
        self.email_lineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.username_lineEdit_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.password_lineEdit_3.setPlaceholderText(_translate("MainWindow", "Password"))
        self.confirm_password_lineEdit_4.setPlaceholderText(_translate("MainWindow", "Confirm password"))
        self.create_account_button.setText(_translate("MainWindow", "Create account"))
        self.register_b_login.setText(_translate("MainWindow", "Login"))
